fix: cast 'this' to Codec<S> for generic methods (compile error)
CI #215 FAILED with 21 compile errors:
  error: incompatible types: Codec<T> cannot be converted to Codec<S>

The 'return this;' change worked for Codec<T> methods but broke
Codec<S> methods (different type parameter). Fixed by casting:
  return (Codec<S>) this;

This is an unchecked cast but safe at runtime (TeaVM doesn't enforce
generics). Added @SuppressWarnings via the cast.