fix: patch SharedConstants.getCurrentVersion to return dummy version
MASSIVE PROGRESS! DataFixers fix worked! Now getting:
  java.lang.IllegalStateException: Game version not set
  at SharedConstants.getCurrentVersion()

The CURRENT_VERSION static field is null because the clinit that sets
it failed (caught by our clinit try/catch wrapper). MC throws
IllegalStateException when it tries to get the version.

Fix: Textual patch of getCurrentVersion to return a dummy version
object with getName() = '26.1.2', getProtocolVersion() = 775,
getDataVersion() = 4189, when CURRENT_VERSION is null.